### PR TITLE
Add ST_Accessibility

### LINKED ISSUE #26: Add ST_Accessibility
Add an SQL function with the following behavior:
- Inputs:
  - `edges`
  - >= 2 destination nodes
- Output: The `nodes` table with the id of the closest destination node (and optionally its distance to this node)
##### Calculation

A naive implementation would use Dijkstra to calculate the distance from each source node to all of the destination nodes and take the min. In practice, this will be too slow.

A better method is the following: 
1. Pick a source node and execute Dijkstra until one of the destination nodes is encountered. This is the closest one. Store its id and distance.
2. For each node on the shortest path from the source node to the newly found destination node, store the id of and distance to the destination.
3. Repeat steps 1-2, except that at each step along Dijkstra, check if the node being examined already has a destination node id. If so, then store the same id, and store the distance to the destination of every node along the shortest path back to the source.

_Note_: This would be rather easy to implement in undirected networks starting from each of the destination nodes (using the calculateShortestPathsFromNode method and an adapted NodeBetweennessInfo). In directed networks, however, we have to start from each of the source nodes.

### PR DESCRIPTION
**Pull request by agouge**
This adds 

``` mysql
ST_Accessibility(output.edges, destination_table | 'dest1, dest2, ...'[, 'weights'][, 'orientation']);
```

where `'orientation'` can be
- 'directed - edge_orientation_column'
- 'reversed - edge_orientation_column' OR
- 'undirected - edge_orientation_column'

The user provides a list of destinations. The function calculates the distance from every node in the graph to each of the possible destinations and chooses the closest destination. This is particularly useful for generating isochrone accessibility maps.

Fixes #26.

### CODE REVIEW

**Comment by agouge** [comment]
P.S. I forgot, I need to add another unit test for using a destination table rather than a list of destinations.

**Comment by agouge** [comment]
And also a unit test for when the orientation is omitted.

**Comment by agouge** [comment]
P.S.S. Sometimes it is possible to have more than one closest destination. For example,

```
    S
  /   \
 /     \
v       v
D1      D2
```

For now, `ST_Accessibility` uses strict inequality when looking for a closer destination and ignores any destinations which have the same distance from a start node. In practice, this ambiguity shouldn't cause much trouble, but it is worth noting.

**Comment by agouge** [comment]
OK, now it should be ready to merge.

**Comment by agouge** [comment]
Some screenshots:
accessibility1
accessibility2

Thanks @gpetit @nicolas-f for helping me figure out how to do an interpolation in OrbisGIS!

**Comment by agouge** [comment]
Note that in the second screenshot above, the red nodes are the ones that belong to a different connected component than the largest connected component.

**Comment by ebocher** [comment]
Perfect. Excellent job

**Pull request merged**
