### PR TITLE
GDMS topology as a GDMS plugin

### PR DESCRIPTION
**Pull request by ebocher**
Adapt gdms_topology to support the new gdms plugin  and update the jgrapht library.

### CODE REVIEW

**Comment by agueganno** [comment]
I thought it was th goal of https://github.com/irstv/gdms-topology-plugin.git

**Comment by ebocher** [comment]
No. https://github.com/irstv/gdms-topology-plugin.git is a plugin for the OrbisGIS-ui that must contains GUI to manage graphes.
But GDMS_topology must works also with gdms. Due to a recent change with must now implement the gdmsplugin class.

**Comment by agouge** [comment]
Is it possible to validate this PR because I need it.
Thx

**Comment by agueganno** [comment]
Sorry for the delay. I do it now.

**Pull request merged**
