### PR TITLE
Replace ST_(M)ShortestPathLength with new implementation (#41)

### PR DESCRIPTION
**Pull request by agouge**
This addresses #41.

I add a function `ST_Distances` (currently for weighted graphs only) which may be used to calculate distances in the following scenarios:
- d(source, destination)
- d(source, *)
- All distances requested in a source-destination table.

The weight column name is an optional String argument. If omitted, the graph is considered unweighted. (But don't omit it for now, since this has not yet been implemented!)

The graph orientation is also an optional **String** argument, which may take on the values
- 'directed'
- 'reversed'
- 'undirected'

I think making the user enter a String will be much more evocative and readable than using 1, 2 and 3 to represent orientations.

If a graph is directed (or reversed), we may also specify individual edge orientations by integers
- 1 (directed)
- -1 (reversed)
- 0 (undirected) 

**in a column named 'edge_orientation'**. We don't add this to the list of parameters so as to avoid unnecessary clutter. If the graph orientation is omitted, it is assumed to be directed.

The unit tests cover the case of a weighted directed graph. It remains to implement this for unweighted graphs and write unit tests for the other cases.
#### Possible signatures

``` mysql
ST_Distances(edges, source_dest_table OR source[, destination][, 'weights'][, 'orientation']);
```
#### Calculate the distances to all reachable nodes

``` mysql
-- Total nodes: 10 993.
-- 0. Directed, oriented by geometries (88)
CREATE TABLE dir_geom AS SELECT * FROM ST_Distances(routes.edges, 4663, 'weight', 'directed');
-- 1. Directed, individual edge orientations (10 607)
-- Update with the edge orientations.
ALTER TABLE routes.edges ADD COLUMN edge_orientation int;
UPDATE routes.edges SET edge_orientation=1 WHERE SENS='Direct';
UPDATE routes.edges SET edge_orientation=-1 WHERE SENS='Inverse';
UPDATE routes.edges SET edge_orientation=0 WHERE SENS='Double';
CREATE TABLE dir_edges AS SELECT * FROM ST_Distances(routes.edges, 4663, 'weight', 'directed');
-- 2. Reversed, individual edge orientations. (10 547)
CREATE TABLE rev_edges AS SELECT * FROM ST_Distances(routes.edges, 4663, 'weight', 'reversed');
-- 3. Undirected (10 741)
CREATE TABLE undir AS SELECT * FROM ST_Distances(routes.edges, 4663, 'weight', 'undirected');
-- Recover the geometries.
CREATE TABLE color_by_distance AS SELECT a.the_geom, b.source, b.destination, b.distance FROM routes.nodes a, undir b WHERE a.id=b.destination;
```

### CODE REVIEW

**Comment by agouge** [comment]
Note that even though this hasn't been implemented for unweighted graphs yet (using BFS), we can still achieve this in its current state by specifying a weight of 1.0 for each edge.

**Comment by agouge** [comment]
For now, if a node is unreachable, it is simply ignored. I think we should still return it in the results set but with a distance of Infinity.

**Comment by ebocher** [comment]
What do you mean about "if a node is unreachable"?

**Comment by ebocher** [comment]
Could you please explain me why you set a litteral string for the orientation ?
CREATE TABLE dir_geom AS SELECT \* FROM ST_Distances(routes.edges, 4663, 'weight', 'directed');
Is this supported : 

Directed, direcTED, DIRECTED.

**Comment by agouge** [comment]
In directed graphs, some nodes cannot be reached from other nodes. Example:

```
2 --> 3 --> 5
```

Here 3 is reachable from 2 since there is an edge (and hence a path) from 2 to 3. However, 2 is not reachable from 5 since there is no path from 5 to 2.

**Comment by agouge** [comment]
I think that making the user write

``` mysql
ST_Distances(routes.edges, 4663, 'weight', 'directed')
```

is much clearer than making him write

``` mysql
ST_Distances(routes.edges, 4663, 'weight', 1)
```

The choice of numbers 1, 2, 3 (or, e.g., 1, -1, 0) is entirely arbitrary and makes scripts harder to read. What do you think @gpetit ?

For now I only "directed", etc., is supported (I use `String#equals()`), but I could easily update this to support what you describe. Note, however, that the former system of using 1, 2, 3 allows the user no room for error and he could easily confuse the numbers. On the other hand, it is pretty difficult to confuse 'directed', 'reversed' and 'undirected'.

**Comment by agouge** [comment]
This does pose problems of backward compatibility with old scripts using the old ST_ShortestPathLength function. But then again, we are going to increment the version number of GDMS-Topology from 1.2 to 1.3.

One of the original motivating factors for changing from 1,2,3 to 'directed', 'reversed', 'undirected' was to facilitate overloading this function. That is, this was the easiest way I found to create one ST_ShortestPathLength that could be called using many different signatures (and avoid having both ST_ShortestPathLength and ST_MShortestPathLength). When using the old system of using numbers for orientations, we ran into cases of ambiguity that could not be resolved.

For example, if we call

``` mysql
ST_ShortestPathLength(routes.edges, 37, 2)
```

do we mean the shortest path from node 37 to node 2 (in an unweighted directed graph), or rather all shortest paths from 37 (in an unweighted edge-reversed graph)?

**Comment by ebocher** [comment]
Ok to increment the GDMS lib. 
do we mean the shortest path from node 37 to node 2 (in an unweighted directed graph), or rather all shortest paths from 37 (in an unweighted edge-reversed graph)?
+1:

**Comment by agouge** [comment]
As of ad4982a, "Directed, direcTED, DIRECTED" etc. are supported. We ignore case.

**Comment by ebocher** [comment]
ok thanks I'm waiting just the column edge orientation argument and it will be ok

**Comment by agouge** [comment]
Ok working on it! :)

**Comment by agouge** [comment]
As of 4d91259, to specify orientation, the user must enter

```
'directed - edge_orientation_column' | 'reversed - edge_orientation_column' | 'undirected'
```

That is, in the case of directed or reversed graphs, the user **must** specify the name of the edge orientations column. The global orientation and the edge orientation column name are written together as a single string separated by a "-".

I'm still adding a few small improvements.

**Comment by agouge** [comment]
As of 8404507, edge orientations other than 1,0,-1 result in the edge being ignored. The edge is not added to the graph, and the user warned about each ignored edge.

**Comment by agouge** [comment]
4893f27 better explains the usage. Now the `getSQLOrder()` method returns

``` mysql
-- Compute the distance from source to destination.
(1) SELECT * FROM ST_ShortestPathLength(output.edges, source, destination[, 'weights_column'][, 'directed - edge_orientation_column' | 'reversed - edge_orientation_column' | 'undirected']);
-- Compute the distance from source to all reachable nodes.
(2) SELECT * FROM ST_ShortestPathLength(output.edges, source[, 'weights_column'][, 'directed - edge_orientation_column' | 'reversed - edge_orientation_column' | 'undirected']);
-- Compute the distances from the sources to the destinations in the source-destination table.
(3) SELECT * FROM ST_ShortestPathLength(output.edges, source_dest_table[, 'weights_column'][, 'directed - edge_orientation_column' | 'reversed - edge_orientation_column' | 'undirected']);
```

I'm ready to merge.

**Comment by ebocher** [comment]
Just a question.

Why do not used a comma separator instead of 

'directed - edge_orientation_column' | 'reversed - edge_orientation_column' | 'undirected'

**Comment by ebocher** [comment]
Ok I will test

**Comment by agouge** [comment]
Good question.

I came to this conclusion because
1. It reduces the number of parameters in the function signature and facilitates overloading the function.
2. It **forces** the user to specify edge orientations if the graph is to be considered directed or reversed.

I know it looks a little funny but it makes sense to me! We can change this later if you want to.

**Comment by ebocher** [comment]
It works below  a full example for a simple use case. +2000 Adam.

``` sql
--Create the graph
CALL ST_GRAPH(TRONCON_ROUTE, 0.01, false, 'route');

--Set the coding orientations
alter table route.edges add column orientation INTEGER ;
update route.edges set orientation = 0 where SENS='Double sens';
update route.edges set orientation = 1 where SENS='Sens unique';
update route.edges set orientation =-1 where SENS='Sens inverse';

--Set the cost column
alter table route.edges add column cost DOUBLE  ;
update route.edges set cost = ST_LENGTH(the_geom);

--Compute the distances between on node for all others
create table result as SELECT * FROM ST_ShortestPathLength(route.edges, 7772, 'cost', 'directed - orientation');

--Join with the original table nodes to display in a map the result
create table distanceNodes as select a.*, b.destination, b.distance from route.nodes as a, result as b where a.id=b.destination;

--Build a map interpolation
create table distanceMap as select * from ST_INTERPOLATE(distanceNodes, 1000, 'distance');

```

**Pull request merged**
