### PR TITLE
Refactor ST_ConnectedComponents

### LINKED ISSUE #21: ST_ConnectedComponents crashes when orientation is not specified.
If the optional argument `orientation` is omitted, we get an ArrayIndexOutOfBounds error.

### PR DESCRIPTION
**Pull request by agouge**
Refactor ST_ConnectedComponents to use the new function helpers and to not crash when the optional argument `orientation` is omitted.
Fixes #21.
Merge #22 first.

### CODE REVIEW

**Comment by agueganno** [comment]
Not much to say about it. The code looks clean, it compiles and test pass. I merge it.

**Comment by agueganno** [comment]
well, no. I must review #19 and #22 first, I guess.

**Comment by agouge** [comment]
This PR includes those other two but builds upon them, so it might be nice to merge them first.

**Comment by agueganno** [comment]
Having a look at your history, what I understand is that you've got all of them merged in this one. Am I wrong ? If I'm not, we shouldn't miss anything by merging directly this one.  But well, that won't change much things ;-) It's as you wish, so.

**Comment by agouge** [comment]
You are correct. We might as well just merge this directly. In the commit message, it would be nice to include the following description:
- Convert ST_ConnectedComponents to a table function and make orientation an optional argument.
- Add FunctionHelpers to facilitate writing SQL functions

**Comment by agueganno** [comment]
OK, I'll do that. BTW, I wonder if Github will consider the two others as closed as well. We'll see :-)

**Comment by agouge** [comment]
Ah I just closed them.
Let me reopen them first.

**Comment by agouge** [comment]
Ready!

**Pull request merged**
